version: '3'

services:
  back-end:
    build: backend
    expose:
      - "4000"
    links:
      - mongo

  front-end:
    build: frontend
    ports:
      - "80:8080"

  mongo:
    image: mongo:latest
    expose:
      - "27017"
