version: '3'

services:
  back-end:
    build: backend
    ports:
      - "4000:4000"
    links:
      - mongo

  front-end:
    build: frontend
    ports:
      - "8080:80"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
