version: '3'

services:
  back-end:
    build: backend
    ports:
      - "4000:4000"
    links:
      - mongo

  front-end:
    build: frontend
    ports:
      - "80:8080"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  recsys_api:
    build: api
    image: recbole_recommender
    command:  uvicorn server:app --reload --workers 1 --host 0.0.0.0 --port 8888
    ports:
      - "8888:8888"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
